// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentBlock } from "./ContentBlock";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * The server's response to a tool call.
 */
export type CallToolResult = { content: Array<ContentBlock>, isError?: boolean | null, structuredContent?: JsonValue | null, };
