// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResponseItem } from "./ResponseItem";

/**
 * Response payload for `Op::GetHistory` containing the current session's
 * in-memory transcript.
 */
export type ConversationHistoryResponseEvent = { conversation_id: string, entries: Array<ResponseItem>, };
