// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExecCommandEndEvent = { 
/**
 * Identifier for the ExecCommandBegin that finished.
 */
call_id: string, 
/**
 * Captured stdout
 */
stdout: string, 
/**
 * Captured stderr
 */
stderr: string, 
/**
 * Captured aggregated output
 */
aggregated_output: string, 
/**
 * The command's exit code.
 */
exit_code: number, 
/**
 * The duration of the command execution.
 */
duration: string, 
/**
 * Formatted output from the command, as seen by the model.
 */
formatted_output: string, };
