// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Encoding } from "./Encoding";
import type { ExecOutputStream } from "./ExecOutputStream";

export type ExecCommandOutputDeltaEvent = { 
/**
 * Identifier for the ExecCommandBegin that produced this chunk.
 */
call_id: string, 
/**
 * Which stream produced this chunk.
 */
stream: ExecOutputStream, 
/**
 * Chunk of output. If binary, this is base64-encoded and `encoding` is "base64".
 */
chunk: string, 
/**
 * Encoding of the chunk data.
 */
encoding: Encoding | null, };
