// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileChange = { "add": { content: string, } } | { "delete": { content: string, } } | { "update": { unified_diff: string, move_path: string | null, } };
