// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistoryEntry } from "./HistoryEntry";

export type GetHistoryEntryResponseEvent = { offset: number, log_id: bigint, 
/**
 * The entry at the requested offset, if available and parseable.
 */
entry: HistoryEntry | null, };
