// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Annotations } from "./Annotations";

/**
 * An image provided to or from an LLM.
 */
export type ImageContent = { annotations?: Annotations | null, data: string, mimeType: string, type: string, };
