// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomPrompt } from "./CustomPrompt";

/**
 * Response payload for `Op::ListCustomPrompts`.
 */
export type ListCustomPromptsResponseEvent = { custom_prompts: Array<CustomPrompt>, };
