// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tool } from "./Tool";

/**
 * Response payload for `Op::ListMcpTools`.
 */
export type McpListToolsResponseEvent = { 
/**
 * Fully qualified tool name -> tool definition.
 */
tools: { [key in string]?: Tool }, };
