// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpInvocation } from "./McpInvocation";

export type McpToolCallBeginEvent = { 
/**
 * Identifier so this can be paired with the McpToolCallEnd event.
 */
call_id: string, invocation: McpInvocation, };
