// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileChange } from "./FileChange";

export type PatchApplyBeginEvent = { 
/**
 * Identifier so this can be paired with the PatchApplyEnd event.
 */
call_id: string, 
/**
 * If true, there was no ApplyPatchApprovalRequest for this patch.
 */
auto_approved: boolean, 
/**
 * The changes to be applied.
 */
changes: { [key in string]?: FileChange }, };
