// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PatchApplyEndEvent = { 
/**
 * Identifier for the PatchApplyBegin that finished.
 */
call_id: string, 
/**
 * Captured stdout (summary printed by apply_patch).
 */
stdout: string, 
/**
 * Captured stderr (parser errors, IO failures, etc.).
 */
stderr: string, 
/**
 * Whether the patch was applied successfully.
 */
success: boolean, };
