// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Annotations } from "./Annotations";

/**
 * A resource that the server is capable of reading, included in a prompt or tool call result.
 *
 * Note: resource links returned by tools are not guaranteed to appear in the results of `resources/list` requests.
 */
export type ResourceLink = { annotations?: Annotations | null, description?: string | null, mimeType?: string | null, name: string, size?: bigint | null, title?: string | null, type: string, uri: string, };
