// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentItem } from "./ContentItem";
import type { FunctionCallOutputPayload } from "./FunctionCallOutputPayload";
import type { LocalShellAction } from "./LocalShellAction";
import type { LocalShellStatus } from "./LocalShellStatus";
import type { ReasoningItemContent } from "./ReasoningItemContent";
import type { ReasoningItemReasoningSummary } from "./ReasoningItemReasoningSummary";
import type { WebSearchAction } from "./WebSearchAction";

export type ResponseItem = { "type": "message", id: string | null, role: string, content: Array<ContentItem>, } | { "type": "reasoning", id: string, summary: Array<ReasoningItemReasoningSummary>, content?: Array<ReasoningItemContent> | null, encrypted_content: string | null, } | { "type": "local_shell_call", 
/**
 * Set when using the chat completions API.
 */
id: string | null, 
/**
 * Set when using the Responses API.
 */
call_id: string | null, status: LocalShellStatus, action: LocalShellAction, } | { "type": "function_call", id: string | null, name: string, arguments: string, call_id: string, } | { "type": "function_call_output", call_id: string, output: FunctionCallOutputPayload, } | { "type": "custom_tool_call", id: string | null, status?: string | null, call_id: string, name: string, input: string, } | { "type": "custom_tool_call_output", call_id: string, output: string, } | { "type": "web_search_call", id: string | null, status?: string | null, action: WebSearchAction, };
