// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationId } from "./ConversationId";
import type { EventMsg } from "./EventMsg";

export type ResumeConversationResponse = { conversationId: ConversationId, model: string, initialMessages: Array<EventMsg> | null, };
