// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The sender or recipient of messages and data in a conversation.
 */
export type Role = "assistant" | "user";
