// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventMsg } from "./EventMsg";

export type SessionConfiguredEvent = { 
/**
 * Unique id for this session.
 */
session_id: string, 
/**
 * Tell the client what model is being queried.
 */
model: string, 
/**
 * Identifier of the history log file (inode on Unix, 0 otherwise).
 */
history_log_id: bigint, 
/**
 * Current number of entries in the history log.
 */
history_entry_count: number, 
/**
 * Optional initial messages (as events) for resumed sessions.
 * When present, UIs can use these to seed the history.
 */
initial_messages: Array<EventMsg> | null, };
