// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Annotations } from "./Annotations";

/**
 * Text provided to or from an LLM.
 */
export type TextContent = { annotations?: Annotations | null, text: string, type: string, };
