// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TokenUsage = { input_tokens: bigint, cached_input_tokens: bigint, output_tokens: bigint, reasoning_output_tokens: bigint, total_tokens: bigint, };
