// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolAnnotations } from "./ToolAnnotations";
import type { ToolInputSchema } from "./ToolInputSchema";
import type { ToolOutputSchema } from "./ToolOutputSchema";

/**
 * Definition for a tool the client can call.
 */
export type Tool = { annotations?: ToolAnnotations | null, description?: string | null, inputSchema: ToolInputSchema, name: string, outputSchema?: ToolOutputSchema | null, title?: string | null, };
