// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A JSON Schema object defining the expected parameters for the tool.
 */
export type ToolInputSchema = { properties?: JsonValue | null, required?: Array<string> | null, type: string, };
