// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanItemArg } from "./PlanItemArg";

export type UpdatePlanArgs = { explanation: string | null, plan: Array<PlanItemArg>, };
