// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputMessageKind } from "./InputMessageKind";

export type UserMessageEvent = { message: string, kind: InputMessageKind | null, };
